import { NgModule } from '@angular/core'
import { CommonModule } from '@angular/common'

// Directives
import {
  AlphabetDirective,
  CapsLockDirective,
  ClickStopPropagationDirective,
  DropzoneDirective,
  EqualValidator,
  FileValidator,
  LowercaseDirective,
  NgVarDirective,
  SlugifyDirective,
  UppercaseDirective,
  UrlValidator,
} from './directives'

// Pipes

import {
  ArrayLengthPipe,
  ColorNegativePipe,
  DuplicatedPipe,
  FileExtPipe,
  FileNamePipe,
  FilterPipe,
  FindIndexPipe,
  FindPipe,
  HtmlDecoderPipe,
  HtmlStripPipe,
  IncludesPipe,
  JoinPipe,
  MapPipe,
  ObjectKeysPipe,
  OrderByPipe,
  ParseNumberPipe,
  PercentagePipe,
  SecurePipe,
  SortPipe,
  SplitPipe,
  SumPipe,
  TimePipe,
  TimestampPipe,
  UnitConversionPipe,
  WrapPipe,
} from './pipes'

@NgModule({
  imports: [CommonModule],
  declarations: [
    // Directives
    AlphabetDirective,
    CapsLockDirective,
    ClickStopPropagationDirective,
    DropzoneDirective,
    NgVarDirective,
    EqualValidator,
    FileValidator,
    LowercaseDirective,
    SlugifyDirective,
    UppercaseDirective,
    UrlValidator,

    // Pipes
    ArrayLengthPipe,
    ColorNegativePipe,
    DuplicatedPipe,
    FilterPipe,
    FindIndexPipe,
    FindPipe,
    HtmlDecoderPipe,
    HtmlStripPipe,
    IncludesPipe,
    JoinPipe,
    MapPipe,
    ObjectKeysPipe,
    OrderByPipe,
    ParseNumberPipe,
    PercentagePipe,
    SecurePipe,
    SortPipe,
    SplitPipe,
    SumPipe,
    TimePipe,
    TimestampPipe,
    UnitConversionPipe,
    WrapPipe,
    FileNamePipe,
    FileExtPipe,
  ],
  exports: [
    // Directives
    AlphabetDirective,
    CapsLockDirective,
    ClickStopPropagationDirective,
    DropzoneDirective,
    NgVarDirective,
    EqualValidator,
    FileValidator,
    LowercaseDirective,
    SlugifyDirective,
    UppercaseDirective,
    UrlValidator,

    // Pipes
    ArrayLengthPipe,
    ColorNegativePipe,
    DuplicatedPipe,
    FileExtPipe,
    FileNamePipe,
    FilterPipe,
    FindIndexPipe,
    FindPipe,
    HtmlDecoderPipe,
    HtmlStripPipe,
    IncludesPipe,
    JoinPipe,
    MapPipe,
    ObjectKeysPipe,
    OrderByPipe,
    ParseNumberPipe,
    PercentagePipe,
    SecurePipe,
    SortPipe,
    SplitPipe,
    SumPipe,
    TimePipe,
    TimestampPipe,
    UnitConversionPipe,
    WrapPipe,
  ],
})
export class NgxToolkitModule {}
